name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  firebase_messaging:
  carousel_slider: ^2.0.0
  cloud_firestore: ^0.13.5
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
